[project]
name = "sptubebot"
version = "0.1.0"
description = "A high-performance Telegram bot for downloading songs from Spotify, SoundCloud, Apple Music and YouTube in premium quality."
requires-python = ">=3.13"
dependencies = [
     "httpx>=0.28.1",
     "orjson>=3.11.2",
     "pycryptodome>=3.23.0",
     "pydantic>=2.11.7",
     "pymongo>=4.14.1",
     "pytdbot>=0.9.5",
     "python-dotenv>=1.1.1",
     "tdjson>=1.8.51",
     "ujson~=5.11.0",
     "yt-dlp>=2025.8.20",
]

[project.license]
file = "LICENSE"


[project.scripts]
start = "src.__main__:main"

[tool.uv]
package = true

[tool.setuptools]
packages = [
    "src",
]
